### ISSUE TITLE
[v.0.11.0.0] Build fails due to "monero-utils-deserialize"

### ISSUE THREAD

**Issue by HobbinHood** [sammy007/homebrew-cryptonight#10]
When I try to upgrade to or install the most recent version 0.11.0.0 of monero, it fails with a 'No such file or directory' error pointing at 'monero-utils-deserialize':

    $ brew upgrade monero --build-from-source
    ==> Upgrading sammy007/cryptonight/monero 
    […]
    ==> make release
    Error: No such file or directory - ./build/release/bin/monero-utils-deserialize

According to hyc and iDunk on the #monero IRC-channel, the program is not part of the default build anymore.
> 16:03 hyc
> that program is only in debug builds now
> 16:04 iDunk
> monero-utils-deserialize was taken out of the default build. The homebrew thing may need updating.

Yet, I can't find anything in the homebrew formula pointing at this program. I don't understand, when it is trying to reference this program/file. I went into the download directory and search for the program name inside the files, but no such luck.
Any ideas what's causing this behaviour?

In the meantime, I figured out a way around this, using the debug mode and ignoring the errors, see below:

    $ brew install monero --build-from-source --debug
    […]
    ==> make release
    /usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
    Errno::ENOENT: No such file or directory - ./build/release/bin/monero-utils-deserialize
    1. raise
    2. ignore
    3. backtrace
    4. irb
    5. shell
    Choose an action: 2                                                                               
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:519:in `rename'
    Errno::ENOENT: No such file or directory - (./build/release/bin/monero-utils-deserialize, /usr/local/Cellar/monero/0.11.0.0/bin/monero-utils-deserialize)
    1. raise
    2. ignore
    3. backtrace
    4. irb
    5. shell
    Choose an action: 2
    Fixing /usr/local/Cellar/monero/0.11.0.0/bin/monero-blockchain-export permissions from 755 to 555
    Fixing /usr/local/Cellar/monero/0.11.0.0/bin/monero-blockchain-import permissions from 755 to 555
    Fixing /usr/local/Cellar/monero/0.11.0.0/bin/monero-wallet-cli permissions from 755 to 555
    Fixing /usr/local/Cellar/monero/0.11.0.0/bin/monero-wallet-rpc permissions from 755 to 555
    Fixing /usr/local/Cellar/monero/0.11.0.0/bin/monerod permissions from 755 to 555
    /usr/local/Homebrew/Library/Homebrew/postinstall.rb (Formulary::FromPathLoader): loading     /usr/local/Homebrew/Library/Taps/sammy007/homebrew-cryptonight/monero.rb
    🍺  /usr/local/Cellar/monero/0.11.0.0: 9 files, 117.3MB, built in 121 minutes 43 seconds

**Comment by sammy007** [comment]
Try `brew upgrade monero` it always builds from source, I don't publish bottles.

**Comment by HobbinHood** [comment]
Yeah, I know. Just a habit to put --build-from-source. It shouldn't do any difference, if there are no bottles. Tested it and it didn't.

**Comment by sammy007** [comment]
Try without `--debug` i wonder if it triggers some special build target in 0.11. I just uninstalled monero and installed it again with `brew install monero` and it works for me. Not an expert in brew, the goal of this tap is to provide dead stupid formula.

**Comment by HobbinHood** [comment]
Uhm, sorry for somehow confusing you. I am using the --debug flag only as a workaround to be able to ignore the errors make is throwing regarding the non-existent deserialize program. Running straight `brew install monero` will result in the error. Not an expert either. And yeah, I like to KISS, too. Using brew because of that.

Maybe I should ask around elsewhere pointing to this issue.

Oh, btw: Thank you for keeping this formula updated \o/

**Comment by sammy007** [comment]
```
==> Installing monero from sammy007/cryptonight
==> Installing dependencies for sammy007/cryptonight/monero: boost
==> Installing sammy007/cryptonight/monero dependency: boost
==> Downloading https://homebrew.bintray.com/bottles/boost-1.65.1.el_capitan.bottle.tar.gz
==> Downloading from ...
######################################################################## 100.0%
==> Pouring boost-1.65.1.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/boost/1.65.1: 12,679 files, 404.3MB
==> Installing sammy007/cryptonight/monero
==> Downloading https://github.com/monero-project/monero/archive/v0.11.0.0.tar.gz
Already downloaded: /Users/me/Library/Caches/Homebrew/monero-0.11.0.0.tar.gz
==> make release
🍺  /usr/local/Cellar/monero/0.11.0.0: 8 files, 108.3MB, built in 14 minutes 41 seconds
```

**Comment by sammy007** [comment]
To see errors you can use `-v` flag.

**Comment by HobbinHood** [comment]
Why didn't I think of the verbose flag /o\
It shows, that the building process actually finishes, if 100% can be said to be finished. Directly after that it shows the error. Probably while trying to install/copying the deserialize program. But for the hell of it, I can't figure out why it would even look for that file respectively even try to install it.

    …
    [ 98%] Linking CXX executable ../../bin/monero-wallet-cli
    [ 98%] Built target simplewallet
    [100%] Linking CXX executable ../../bin/monerod
    [100%] Built target daemon
    Error: No such file or directory - ./build/release/bin/monero-utils-deserialize

**Comment by sammy007** [comment]
Are you sure you are installing 0.11? I need a log full log.

**Comment by HobbinHood** [comment]
Sorry, somehow I managed to always crop out the part where it says, downloading and which version/file.
Yeah, 100% positive it is downloading and building 0.11, hence it's installed now, due to the workaround going the `--debug` route and ignore errors.
