### ISSUE TITLE
Install from source fails

### ISSUE THREAD

**Issue by jfreeze** [sammy007/homebrew-cryptonight#12]
The build fails with an error that it is missing miniupnpc.h. miniupnpc is installed and miniupnpc.h is located at 

/usr/local/Cellar/miniupnpc/2.0.20170509/include/miniupnpc/miniupnpc.h

$ brew install monero --build-from-source
==> Installing monero from sammy007/cryptonight
==> Downloading https://github.com/monero-project/monero/archive/v0.11.1.0.tar.gz
==> Downloading from https://codeload.github.com/monero-project/monero/tar.gz/v0.11.1.0
######################################################################## 100.0%
==> make release
Last 15 lines from /Users/jimfreeze/Library/Logs/Homebrew/monero/01.make:
In file included from /tmp/monero-20171101-9275-azk43q/monero-0.11.1.0/src/rpc/core_rpc_server.cpp:34:
In file included from /tmp/monero-20171101-9275-azk43q/monero-0.11.1.0/src/rpc/core_rpc_server.h:39:
In file included from /tmp/monero-20171101-9275-azk43q/monero-0.11.1.0/src/p2p/net_node.h:338:
/tmp/monero-20171101-9275-azk43q/monero-0.11.1.0/contrib/epee/include/net/../../../../src/p2p/net_node.inl:58:12: fatal error: 'miniupnpc.h' file not found
  #include "miniupnpc.h"
           ^~~~~~~~~~~~~
[ 71%] Built target obj_common
1 error generated.
make[3]: *** [src/rpc/CMakeFiles/obj_rpc.dir/core_rpc_server.cpp.o] Error 1
make[2]: *** [src/rpc/CMakeFiles/obj_rpc.dir/all] Error 2
[ 71%] Built target obj_blockchain_db
[ 71%] Built target obj_cryptonote_basic
[ 71%] Built target obj_mnemonics
make[1]: *** [all] Error 2
make: *** [release] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/sammy007/homebrew-cryptonight/issues

**Comment by andrewdoh** [comment]
got the same issue, just wanted to leave a comment so it wouldn't be marked as a isolated incident.

**Comment by sammy007** [comment]
Try just `brew install monero` for now.

**Comment by sammy007** [comment]
Well, maybe something broken in master as well.

**Comment by Michu44** [comment]
@sammy007 I got the same issue on mac version 10.13.1 (17B1003)

**Comment by bcometa** [comment]
Realized the other "issue" is same as this one. I tried "brew install monero" and it completed succcessfully. But, I don't know the next step to get Aeon to work. I also don't see any monero files on my computer, but probably not looking in the right place. 

If any devs can help fix this, I'll be responsive in helping (as best as I can), since right now I have a lot of AEON on an exchange which does not feel safe.
