### ISSUE TITLE
Request: Update Brew for Aeon Rebase POW change and LMDB addition

### ISSUE THREAD

**Issue by BigslimVdub** [sammy007/homebrew-cryptonight#15]
Aeon is Forking approximately May 28th to new V1 POW change. Also Aeon is adding LMDB. Can you update BREW to accommodate these needed changes for compiling on osx? Brew is far easier for compiling. 

I did have a writeup for compiling using Cmake but it seems brew does a better job and faster on lower end hardware (ie; MBA).

Many additional dependencies are needed for the rebase but the base ones are basically the same as needed for 0.9.14 aeon repo.

**Comment by sammy007** [comment]
Aeon's Latest commit 17ee55f  on Jan 9.

**Comment by BigslimVdub** [comment]
Yes, rebase version is being merged soon: https://github.com/aeonix/aeon-rebase/pull/7

Just wanted to inform so additions could be made when available. Thank you.
