### ISSUE TITLE
Installing from brew not working

### ISSUE THREAD

**Issue by songproducer** [sammy007/homebrew-cryptonight#7]
Leos-MacBook-Pro:aeon-0.9.6.0 leotreasure$ brew install --HEAD aeon
==> Installing aeon from sammy007/cryptonight
==> Installing dependencies for sammy007/cryptonight/aeon: cmake
==> Installing sammy007/cryptonight/aeon dependency: cmake
==> Downloading https://homebrew.bintray.com/bottles/cmake-3.4.3.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring cmake-3.4.3.el_capitan.bottle.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/cmake
==> Summary
🍺  /usr/local/Cellar/cmake/3.4.3: 1,980 files, 27.4M
==> Installing sammy007/cryptonight/aeon
==> Cloning https://github.com/aeonix/aeon.git
Cloning into '/Library/Caches/Homebrew/aeon--git'...
remote: Counting objects: 541, done.
remote: Compressing objects: 100% (420/420), done.
remote: Total 541 (delta 138), reused 372 (delta 101), pack-reused 0
Receiving objects: 100% (541/541), 5.97 MiB | 989.00 KiB/s, done.
Resolving deltas: 100% (138/138), done.
Checking connectivity... done.
==> Checking out branch master
==> make
Last 15 lines from /Users/leotreasure/Library/Logs/Homebrew/aeon/01.make:
[ 43%] Building CXX object src/CMakeFiles/cryptonote_core.dir/cryptonote_core/cryptonote_core.cpp.o
[ 44%] Building CXX object src/CMakeFiles/cryptonote_core.dir/cryptonote_core/cryptonote_format_utils.cpp.o
[ 45%] Linking CXX static library libcommon.a
[ 45%] Built target common
[ 46%] Building CXX object src/CMakeFiles/cryptonote_core.dir/cryptonote_core/difficulty.cpp.o
[ 47%] Building CXX object src/CMakeFiles/cryptonote_core.dir/cryptonote_core/miner.cpp.o
[ 47%] Building CXX object src/CMakeFiles/cryptonote_core.dir/cryptonote_core/tx_pool.cpp.o
[ 48%] Linking CXX static library libcryptonote_core.a
[ 48%] Built target cryptonote_core
[ 49%] Linking CXX static library librpc.a
[ 49%] Built target rpc
[ 50%] Linking CXX static library libwallet.a
[ 50%] Built target wallet
make[1]: *** [all] Error 2
make: *** [build-release] Error 2

**Comment by sammy007** [comment]
WFM.

[ 97%] Built target daemon
[ 98%] Building CXX object tests/CMakeFiles/coretests.dir/core_tests/transaction_tests.cpp.o
[ 99%] Building CXX object tests/CMakeFiles/coretests.dir/core_tests/tx_validation.cpp.o
[100%] Linking CXX executable coretests
[100%] Built target coretests
==> Cleaning
==> Finishing up

try to build with -v flag for verbose logging. Make sure brew packages are up to date.

**Comment by GitHayden** [comment]
Same problems occurring here...


[ 42%] Building CXX object src/CMakeFiles/cryptonote_core.dir/cryptonote_core/cryptonote_basic_impl.cpp.o
[ 43%] Building CXX object src/CMakeFiles/cryptonote_core.dir/cryptonote_core/cryptonote_core.cpp.o
[ 44%] Linking CXX static library libcommon.a
[ 44%] Built target common
[ 45%] Building CXX object src/CMakeFiles/cryptonote_core.dir/cryptonote_core/cryptonote_format_utils.cpp.o
[ 46%] Building CXX object src/CMakeFiles/cryptonote_core.dir/cryptonote_core/difficulty.cpp.o
[ 47%] Building CXX object src/CMakeFiles/cryptonote_core.dir/cryptonote_core/miner.cpp.o
[ 47%] Building CXX object src/CMakeFiles/cryptonote_core.dir/cryptonote_core/tx_pool.cpp.o
[ 48%] Linking CXX static library libcryptonote_core.a
[ 48%] Built target cryptonote_core
[ 49%] Linking CXX static library librpc.a
[ 49%] Built target rpc
[ 50%] Linking CXX static library libwallet.a
[ 50%] Built target wallet
make[1]: *** [all] Error 2
make: *** [build-release] Error 2
==> Formula
Tap: sammy007/cryptonight
Path: /usr/local/Library/Taps/sammy007/homebrew-cryptonight/aeon.rb
==> Configuration
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 11d47e8325f50ab7993f3fca0432876da0ea1c11
Last commit: 5 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4f29a9d82684d36ea0c4cf7988a83dc8cef76f43
Core tap last commit: 5 months ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit sandybridge
Clang: 8.0 build 800
Perl: /usr/bin/perl
Python: /Library/Frameworks/Python.framework/Versions/2.7/bin/python => /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.7.0_67
System Ruby: 2.0.0-p648
OS X: 10.12.1-x86_64
Xcode: 8.0
CLT: N/A
X11: 2.6.4 => /opt/X11
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libxml2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/apache2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks
MACOSX_DEPLOYMENT_TARGET: 10.12
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig
HOMEBREW_SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/cmake/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: sammy007/cryptonight/aeon HEAD did not build
Logs:
     /Users/######/Library/Logs/Homebrew/aeon/01.make
     /Users/######/Library/Logs/Homebrew/aeon/01.make.cc

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
#####-MacBook-Pro:aeon-0.9.6.0 #####$

**Comment by sammy007** [comment]
```
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
```
