### ISSUE TITLE
Problem installing wallet on mac - Homebrew.

### ISSUE THREAD

**Issue by harshpokharna** [sammy007/homebrew-cryptonight#9]
Hi Guys,
I followed the steps: - brew tap sammy007/cryptonight - brew install --HEAD aeon
However, I get the following output.
Last 15 lines from /Users/harsh/Library/Logs/Homebrew/aeon/01.make: make[2]: *** [src/CMakeFiles/crypto.dir/all] Error 2 make[2]: *** Waiting for unfinished jobs.... [ 27%] Building CXX object src/CMakeFiles/cryptonote_core.dir/cryptonote_core/checkpoints.cpp.o [ 28%] Building CXX object src/CMakeFiles/cryptonote_core.dir/cryptonote_core/cryptonote_basic_impl.cpp.o [ 29%] Building CXX object src/CMakeFiles/cryptonote_core.dir/cryptonote_core/cryptonote_core.cpp.o [ 29%] Building CXX object src/CMakeFiles/cryptonote_core.dir/cryptonote_core/cryptonote_format_utils.cpp.o [ 30%] Building CXX object src/CMakeFiles/cryptonote_core.dir/cryptonote_core/difficulty.cpp.o [ 31%] Building CXX object src/CMakeFiles/cryptonote_core.dir/cryptonote_core/miner.cpp.o [ 32%] Building CXX object src/CMakeFiles/cryptonote_core.dir/cryptonote_core/tx_pool.cpp.o [ 33%] Linking CXX static library libwallet.a [ 33%] Built target wallet [ 34%] Linking CXX static library libcryptonote_core.a [ 34%] Built target cryptonote_core make[1]: *** [all] Error 2 make: *** [build-release] Error 2
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core): https://github.com/sammy007/homebrew-cryptonight/issues
These open issues may also help: Problem at "brew install --HEAD aeon -v" https://github.com/sammy007/homebrew-cryptonight/issues/8
Can anyone help me here?
Thanks.

**Comment by ArtSabintsev** [comment]
Fixed it: https://github.com/sammy007/homebrew-cryptonight/issues/8#issuecomment-309337939
